services:
  eureka:
    build: ./eureka-service
    ports: ["8761:8761"]

  exchange:
    build: ./exchange-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on: [eureka]
    ports: ["9000:9000"]

  currency:
    build: ./currency-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on: [eureka, exchange]
    ports: ["9100:9100"]

  audit:
    build: ./audit-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on: [eureka]
    ports: ["8200:8200"]
